#!/usr/bin/env python
import os
import sys

dependency_path = os.path.abspath("../dependency_extension")
env = SConscript("../godot-cpp-4.5/SConstruct")

env.Append(CPPPATH=[
    "src/public",
    f"{dependency_path}/src/public",
    ])
env.Append(LIBPATH=[f"{dependency_path}/bin"])
env.Append(LIBS=["libdependency.windows.template_debug.x86_64"])
sources = Glob("src/private/*.cpp")

library = env.SharedLibrary(
    "bin/libmain{}{}".format(env["suffix"], env["SHLIBSUFFIX"]),
    source=sources,
)

Default(library)
